steps:
- name: 'ruby:latest'
  entrypoint: bash
  args:
  - "-c"
  - |
    gem install bundler:2.1.0
    bundle update --bundler
    gem install gem-release --pre
    bundle exec jekyll b
    mv firebase.json _site/
    mv .well-known _site/
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy', '--project', '$PROJECT_ID']
  dir: /workspace/_site
