steps:
  - name: 'ruby:latest'
    entrypoint: bash
    args:
      - "-c"
      - |
        gem install bundler:2.1.0
        bundle update --bundler
        gem install gem-release --pre
        bundle exec jekyll b
        mv firebase.json _site/
  - name: node:10-buster
    id: deploy
    dir: web
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        npm install -g firebase-tools
        firebase deploy --project $PROJECT_ID

